name: .NET CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_CONFIGURATION: Release

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: "22.x"

      - uses: actions/cache@v4
        name: Cache NuGet packages
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('Directory.Packages.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - uses: actions/cache@v4
        name: Cache Docker volumes for ollamazure
        with:
          path: /var/lib/docker/volumes
          key: ${{ runner.os }}-docker-${{ hashFiles('Directory.Docker.props') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Install Aspire workload
        run: dotnet workload install aspire

      - name: Install Ollamazure
        run: npm install -g ollamazure

      - name: Setup .NET dev certs
        run: |
          dotnet tool update -g linux-dev-certs
          dotnet linux-dev-certs install

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration ${{ env.DOTNET_CONFIGURATION }}

      - name: Ensure browsers are installed
        run: pwsh tests/YouTubeGPT.Tests/bin/${{ env.DOTNET_CONFIGURATION }}/net8.0/playwright.ps1 install --with-deps

      - name: Setup local models
        run: dotnet user-secrets set "UseLocalModel" "true" --project src/YouTubeGPT.AppHost/YouTubeGPT.AppHost.csproj

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration ${{ env.DOTNET_CONFIGURATION }} --collect "XPlat Code Coverage" --results-directory test-results --logger trx

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            ${{ github.workspace }}/test-results/**

      - name: Upload Playwright traces
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-traces
          path: |
            ${{ github.workspace }}/tests/YouTubeGPT.Tests/bin/${{ env.DOTNET_CONFIGURATION }}/net8.0/playwright-traces/**
