name: .NET CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_CONFIGURATION: Release

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install Aspire workload
        run: dotnet workload install aspire

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration ${{ env.DOTNET_CONFIGURATION }}

      - name: Ensure browsers are installed
        run: pwsh tests/YouTubeGPT.Tests/bin/${{ env.DOTNET_CONFIGURATION }}/net8.0/playwright.ps1 install --with-deps

      - name: Setup local models
        run: dotnet user-secrets set "UseLocalModel" "true" --project src/YouTubeGPT.AppHost/YouTubeGPT.AppHost.csproj

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration ${{ env.DOTNET_CONFIGURATION }}

      - name: Upload Playwright traces
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-traces
          path: |
            ${{ github.workspace }}/tests/YouTubeGPT.Tests/bin/${{ env.DOTNET_CONFIGURATION }}/net8.0/playwright-traces/**
